### ISSUE TITLE
sonic cd disassembly lvl issue

### ISSUE THREAD

**Issue by frostyerwinters** [Ralakimus/sonic-cd-disassembly#2]
when i try to edit a zone it just says "unhandled exception directorynotfoundexception log file has not been saved, do you want to continue running?" then when i open the zone, nothing happens and the application either freezes or crashes, apparently it works when i open it using the lvl editor from the sonic 1 disassembly? decided to finally check into the sonic lvl file notepad and got this,
Operating system: Microsoft Windows NT 6.2.9200.0
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\Downloads\sonic-cd-disassembly-main\sonic-cd-disassembly-main\HUD\HUD.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at SonicRetro.SonLVL.API.IniSerializer.Deserialize[T](String filename) in C:\Programs\SonLVL\SonLVLAPI\IniSerializer.cs:line 169
   at SonicRetro.SonLVL.GUI.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 222
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Ralakimus** [comment]
"HUD\HUD.ini" is a file for configuring the HUD font in SonLVL. I am assuming you just copied SonLVL.exe over to the disassembly. I personally do not recommend this. Instead put SonLVL and all of its data into a separate folder and just run the EXE from there and load the disassembly's SonLVL.ini file from there.

**Comment by frostyerwinters** [comment]
thanks dude! ill leave another reply if your tip works

**Comment by frostyerwinters** [comment]
hey dude! your tip worked! but now i have another problem, i cant run and build, despite using many emulators meant for the sega cd any idea why it doesnt work?

**Comment by Ralakimus** [comment]
The disassembly is incomplete and doesn't supply the files that aren't disassembled yet. You will need to get a copy of Sonic CD and copy them over into the build process yourself.

**Comment by frostyerwinters** [comment]
where should i get a copy of sonic cd? doesnt the only official version cost? and whats your recommendation for where i can find a download for the game.

**Comment by Ralakimus** [comment]
You'll need to get a copy or rip of the original Sega CD version of Sonic CD and extract the files from the disc image.

**Comment by frostyerwinters** [comment]
Alright man, take your time, I'll be excited for the full release
